### ISSUE TITLE
Cannot access offset of type string on string in file src/CentrifugoBroadcaster.php on line 91

### ISSUE THREAD

**Issue by ghost** [Opekunov/laravel-centrifugo-broadcaster#12]
```
TypeError: Cannot access offset of type string on string in file /laravel-src/vendor/opekunov/laravel-centrifugo-broadcaster/src/CentrifugoBroadcaster.php on line 91

#0 /laravel-src/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(85): Opekunov\Centrifugo\CentrifugoBroadcaster-&gt;broadcast()
#1 /laravel-src/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Broadcasting\BroadcastEvent-&gt;handle()
#2 /laravel-src/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#3 /laravel-src/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#4 /laravel-src/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#5 /laravel-src/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
#6 /laravel-src/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container-&gt;call()
#7 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher-&gt;Illuminate\Bus\{closure}()
#8 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#9 /laravel-src/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline-&gt;then()
#10 /laravel-src/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php(158): Illuminate\Bus\Dispatcher-&gt;dispatchNow()
#11 /laravel-src/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(320): Illuminate\Broadcasting\BroadcastManager-&gt;queue()
#12 /laravel-src/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(243): Illuminate\Events\Dispatcher-&gt;broadcastEvent()
#13 /laravel-src/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(451): Illuminate\Events\Dispatcher-&gt;dispatch()
#14 /laravel-src/vendor/laravel/framework/src/Illuminate/Foundation/Events/Dispatchable.php(14): event()
#15 /laravel-src/routes/api.php(9): App\Events\IncomingPayloadReceived::dispatch()
#16 /laravel-src/vendor/laravel/framework/src/Illuminate/Routing/CallableDispatcher.php(40): Illuminate\Routing\RouteFileRegistrar-&gt;{closure}()
#17 /laravel-src/vendor/laravel/framework/src/Illuminate/Routing/Route.php(237): Illuminate\Routing\CallableDispatcher-&gt;dispatch()
#18 /laravel-src/vendor/laravel/framework/src/Illuminate/Routing/Route.php(208): Illuminate\Routing\Route-&gt;runCallable()
#19 /laravel-src/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route-&gt;run()
#20 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}()
#21 /laravel-src/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#22 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle()
#23 /laravel-src/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#24 /laravel-src/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequest()
#25 /laravel-src/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequestUsingNamedLimiter()
#26 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle()
#27 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#28 /laravel-src/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline-&gt;then()
#29 /laravel-src/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router-&gt;runRouteWithinStack()
#30 /laravel-src/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router-&gt;runRoute()
#31 /laravel-src/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router-&gt;dispatchToRoute()
#32 /laravel-src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\Routing\Router-&gt;dispatch()
#33 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}()
#34 /laravel-src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#35 /laravel-src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle()
#36 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle()
#37 /laravel-src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#38 /laravel-src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle()
#39 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle()
#40 /laravel-src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#41 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle()
#42 /laravel-src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#43 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle()
#44 /laravel-src/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#45 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors-&gt;handle()
#46 /laravel-src/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#47 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies-&gt;handle()
#48 /laravel-src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#49 /laravel-src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline-&gt;then()
#50 /laravel-src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter()
#51 /laravel-src/public/index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle()
#52 /laravel-src/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(16): require_once('...')
#53 {main}

```

**Comment by alexeyvolodin** [comment]
Check api key. 
or see my pr https://github.com/Opekunov/laravel-centrifugo-broadcaster/pull/13 which fixes wrong error array in exception
